name: Run Go Script

on:
  schedule:
    # Run the job every 1 minute
    - cron: '*/1 * * * *'

jobs:
  run-go-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16  # specify the Go version you are using
      
    - name: Run Go Script
      run: go run main.go
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}